@startuml

	actor main

 	create List
 	main -> List : new

    group foreach concrete BookReader 	
	 	create BookReader
	 	main -> BookReader : new
	 	activate BookReader
	 	BookReader -> BookReader : buyBook()
	 	activate BookReader
	 	create Book
	 	BookReader->Book:new
	 	deactivate BookReader
	 	BookReader --> main
	 	deactivate BookReader
	 	main -> List : add(bookReader)
	end
	
 	loop foreach BookReader in bookReaderList
 		main-> List : getNext()
 		List --> main : reader
 		main -> "BookReader" : displayOwnedBooks()
 	end

	create AdventureBookReader
	main -> AdventureBookReader
	
	main -> AdventureBookReader : buyBook()
	activate AdventureBookReader
	
	create TreasureIsland 
	AdventureBookReader -> TreasureIsland : new
	AdventureBookReader --> main : book
	deactivate AdventureBookReader

@enduml
