@startuml

title Proxy Sequence Diagram

actor main
create ProxyFileHandler

main -> ProxyFileHandler : new(fileName)
main -> ProxyFileHandler : getFileName()
activate ProxyFileHandler
main <-- ProxyFileHandler : fileName
deactivate ProxyFileHandler

main -> ProxyFileHandler : getContent()
activate ProxyFileHandler
create RealFileHandler
    ProxyFileHandler -> RealFileHandler : new(fileName)
    create FileInputStream
    RealFileHandler -> FileInputStream : new (fileName)
    RealFileHandler -> FileInputStream : available()
    activate FileInputStream
    RealFileHandler <-- FileInputStream : numBytes
    RealFileHandler -> FileInputStream : read(content)
    RealFileHandler <-- FileInputStream
    deactivate FileInputStream
    destroy FileInputStream
ProxyFileHandler -> RealFileHandler : getContent()
ProxyFileHandler <-- RealFileHandler : content
main <-- ProxyFileHandler : content
deactivate ProxyFileHandler

main -> ProxyFileHandler : getLine(requestedLine)
activate ProxyFileHandler
alt requestedLine != lineNumber
	ProxyFileHandler -> RealFileHandler : getLine(requestedLine)
	ProxyFileHandler <-- RealFileHandler : lineText
	note right : Cache miss
end
main <-- ProxyFileHandler : lineText

	
deactivate ProxyFileHandler

@enduml
