@startuml
    actor main
	
    create RectangleClassAdapter
    main -> RectangleClassAdapter: new
    main -> RectangleClassAdapter: setId()
    main -> RectangleClassAdapter: define()
    RectangleClassAdapter->RectangleClassAdapter: setShape()
    
    create RectangleObjectAdapter
    main -> RectangleObjectAdapter: new

    create Rectangle
    main -> Rectangle: new

    main -> RectangleObjectAdapter: setId()
    main -> RectangleObjectAdapter: define()
    RectangleObjectAdapter -> Rectangle : setShape()
    
@enduml
