@startuml

	participant main

	participant "ConsoleReader" as reader
	
	alt
	create reader 
		main -> reader : new(Mode.SECURE_MODE_ON)
	else
		main -> reader : new(Mode.SECURE_MODE_OFF)
	end
	actor Console
	
	group try 
	
		main -> reader : readInteger()
		activate reader
			reader -> Console : readLine()
			Console --> reader : String
			create Integer
			group try
				reader -> Integer: new (String)
			else catch
				alt mode == Mode.SECURE_MODE_ON
					create ConsoleReaderException
					reader -> ConsoleReaderException
					reader -[#red]> main : ConsoleReaderException 	
				else 
				    participant "0 : Integer" as 0
				    create 0
					reader -> 0 : new (0)
				end 
			end
			reader --> main : Integer
		deactivate reader
	
	else catch(ConsoleReaderException e)
		main --> Console : "println('WTF?')";
	else finally
		main --> Console : println(text, num, doub)
	end
	
	
@enduml
