@startuml
	actor main

    
    create SinglePart
   	main -> SinglePart : new
    create CompoundPart
   	main -> CompoundPart : new   
   	
   	main -> CompoundPart : add(keyboard)
	activate CompoundPart
 	CompoundPart -> ArrayList : add(child)
    deactivate CompoundPart
    
    main -> SinglePart : describe()
    main -> CompoundPart : describe()
   
	
@enduml